### ISSUE TITLE
Tests that call AIS Messages sometime return different results than expected

### ISSUE THREAD

**Issue by tokanada** [colinthomas-z80/cs498-Monitoring-Ships-At-Sea#4]
For example, on test_read_ship_positions_in_tile (located in david_queries branch), the expected output is:
`[[(9608673, 'Marshall Islands', 'Ionic Hawk', 2012, None, 180, 30, 22432, 538004542, 'Bulk Carrier', 'Active', '20820')], []]`

But randomly the output maybe result in:
`[[], [(9608673, 'Marshall Islands', 'Ionic Hawk', 2012, None, 180, 30, 22432, 538004542, 'Bulk Carrier', 'Active', '20820')]]`

This affects all tests that reference AIS Messages located in sample.json. This makes me believe that it is some weird glitch on insert_message_batch. 

I have implemented a potential workaround in my branch that involves delaying some times before others so that the outputs of each query is more predictable.

**Comment by colinthomas-z80** [comment]
Fixed
